config/routes.rb
Rails.application.routes.draw do

  mount_roboto
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  namespace :admin do
    resources :user, only: [:new, :create, :index]
  end

  namespace :user do
    ################
    # User profile
    ########
    resources :profile, only: [:index, :update]
    # To avoid adding user number as parameter like :id
    get 'profile/edit', to: 'profile#edit'

    ################
    # User project
    ########
    resources :projects
  end

  ################
  # Devise setting
  ########
  devise_for :users, only: [:sign_in, :sign_out, :session, :password]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  # Open Project
  resources :projects, only: [:index, :show]

  root 'static_page#index'
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def index
    @projects = Project.where(is_published: true).order('RANDOM()').limit(4)
  end
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/views/static_page/index.html.erb
<div class="py-5 text-center opaque-overlay" id="_header_image">
  <div class="container py-5">
    <div class="row">
      <div class="col-md-12 text-white">
        <h3 class="display-3 mb-4">とまりぎポートフォリオ</h3>
        <p class="lead mb-5">Start here to further give an impact on the world by TOBITATE association</p>
        <%= link_to 'プロジェクトを見る', projects_path, class: 'btn btn-lg btn-primary mx-1' %>
      </div>
    </div>
  </div>
</div>
<div class="py-5">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="row">
          <% if @projects %>
              <% @projects.each do |project| %>
                <div class="col-md-3 my-5">
                  <%= image_tag(project.image, class: 'img-fluid d-block w-100 mb-3 rounded', onerror: 'this.error=null;this.src="default-thumbnail.jpg"') %>
                  <h5 class="text-center"><%= project.title %></h5>
                  <div class="_description">
                    <%= auto_link(markdown(project.description).truncate(100, omission: '...'), :html => { :target => '_blank' }) %>
                  </div>
                  <%= link_to 'もっと見る', project_path(project.id), :class => 'btn btn-outline-primary text-center w-100' %>
                </div>
              <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="py-5 text-center bg-light">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1 class="pb-3 text-secondary">世界への挑戦、ここから始めよう</h1>
      </div>
    </div>
    <div class="row">
      <div class="text-right col-md-6">
        <div class="row my-5">
          <div class="col-2 order-lg-2 col-2 text-center"><i class="d-block mx-auto fa fa-clone fa-3x"></i></div>
          <div class="col-10 text-lg-right text-left order-lg-1">
            <h4 class="text-primary">プロジェクトを公開する</h4>
            <p class="col-md-8 offset-md-4 p-0">今行なっているプロジェクトを公開して活動を紹介しよう</p>
          </div>
        </div>
        <div class="row my-5">
          <div class="col-2 order-lg-2 col-2 text-center"><i class="d-block fa fa-circle-thin fa-4x"></i></div>
          <div class="col-10 text-lg-right text-left order-lg-1">
            <h4 class="text-primary">人を巻き込む</h4>
            <p class="col-md-8 offset-md-4 p-0">様々な専門分野を持っているトビタテ生と一緒に活動しよう</p>
          </div>
        </div>
      </div>
      <div class="text-left col-md-6">
        <div class="row my-5">
          <div class="col-2 text-center"><i class="d-block fa fa-check-square-o fa-3x" aria-hidden="true"></i></div>
          <div class="col-10">
            <h4 class="text-primary">活動する</h4>
            <p class="col-md-8 p-0">活動した記録をここで公開し、共有しましょう</p>
          </div>
        </div>
        <div class="row my-5">
          <div class="col-2 text-center"><i class="d-block fa  fa-comment-o fa-3x"></i></div>
          <div class="col-10">
            <h4 class="text-primary">応援する</h4>
            <p class="col-md-8 p-0">いろいろな形で、応援できます</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>