config/routes.rb
Rails.application.routes.draw do

  mount_roboto
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  namespace :admin do
    resources :user, only: [:new, :create, :index]
  end

  namespace :user do
    ################
    # User profile
    ########
    resources :profile, only: [:index, :update]
    # To avoid adding user number as parameter like :id
    get 'profile/edit', to: 'profile#edit'

    ################
    # User project
    ########
    resources :projects
  end

  ################
  # Devise setting
  ########
  devise_for :users, only: [:sign_in, :sign_out, :session, :password]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  # Open Project
  resources :projects, only: [:index, :show]

  root 'static_page#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile, dependent: :destroy
  has_many :projects, dependent: :destroy
  accepts_nested_attributes_for :profile

  def admin?
    self.is_admin?
  end

end

app/controllers/admin/user_controller.rb
class Admin::UserController < ApplicationController

  before_action :admin_user

  def index
    @users = User.all
  end

  def new
    @user = User.new
    @user.build_profile
  end

  def create
    @user = User.new(user_params)
    if @user.save
      "user : #{@user.email} and #{@user.profile.name}"
      flash[:success] = 'User was successfully created.'
      redirect_to admin_user_index_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(
        :email, :password, :password_confirmation, :is_admin,
        profile_attributes: [:name, :term]
    )
  end

end

app/controllers/user/application_controller.rb
class User::ApplicationController < ApplicationController
  layout  'user/application'
  before_action :authenticate_user!
end

app/controllers/user/profile_controller.rb
class User::ProfileController < User::ApplicationController

  before_action :set_user, only: [:index, :edit, :update]

  def index
  end

  def edit
  end

  def update
    respond_to do |format|
      if @profile.update(profile_params)
        @profile.save
        format.html { redirect_to user_profile_index_path, notice: 'Profile was successfully updated.' }
        format.json { render :index, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end


  private

    def set_user
      @profile = Profile.find_by(user_id: current_user.id)
    end


    def profile_params
      params.require(:profile).permit([:name, :term])
    end


end

app/controllers/user/projects_controller.rb
class User::ProjectsController < User::ApplicationController

  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.where(:user_id => current_user).order('created_at DESC')
  end

  def new
    @project = Project.new
    @default_value = defalut_value
  end

  def show
  end

  def edit
    @project.main_image.cache! unless @project.main_image.blank?
    @default_value = @project.description
  end

  def create
    @project = current_user.projects.build(project_params)
    if @project.save
      flash[:success] = 'Project was successfully created.'
      redirect_to user_project_path @project
    else
      # Error handling
      render :new
    end
  end

  def update
    if @project.update_attributes(project_params)
      flash[:success] = 'Project was successfully updated.'
      redirect_to user_project_path @project
    else
      render :edit
    end
  end

  def destroy
    if @project.delete
      flash[:success] = 'Project was successfully deleted.'
    else
      render :edit
    end
    redirect_to user_projects_path
  end
  
  private

  def project_params
    params.require(:project).permit([
        :title,
        :main_image,
        :main_image_cache,
        :description,
        :is_published,
        :organization,
        :url,
        :established_at,
        :twitter,
        :facebook
    ])
  end

  def defalut_value
    value = <<-EOS

ここにプロジェクトの概要を記入してください  

マークダウン式の記述方法です。  
改行は半角スペース2つです。  

[リンクの入れ方は](https://google.com)この通り  
**これで太文字の記入**  
*斜文字*
# タイトル1
## タイトル2
### タイトル3
#### タイトル4
##### タイトル5
![画像の入れ方](http://www.mext.go.jp/a_menu/kokusai/tobitate/__icsFiles/artimage/2014/04/21/c_edu08_04/Ryugaku-JAPAN_Logojpg.jpg)

---  
#### 最近の活動
2020/11/11 イベントを行います！    

    EOS
    value
  end

  def set_project
    @project = Project.find(params[:id])
  end
end

app/helpers/admin/user_helper.rb
module Admin::UserHelper
end

app/helpers/user/profile_helper.rb
module User::ProfileHelper
end

app/helpers/user/projects_helper.rb
module User::ProjectsHelper
end

app/views/admin/user/_form.html.erb
<div class="form-group">
  <%= f.label :email %>
  <%= f.text_field :email, class: 'form-control', :required => true %>
</div>
<div class="form-group">
  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control', :required => true %>
</div>
<div class="form-group">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control', :required => true %>
</div>
<div class="form-group">
  <%= f.label :is_admin %>
  <%= f.check_box :is_admin, class: 'form-control' %>
</div>

<%= f.fields_for :profile do |p| %>
    <div class="form-group">
      <%= p.label :name %>
      <%= p.text_field :name, class: 'form-control', :required => true %>
    </div>
    <div class="form-group">
      <%= p.label :term, 'トビタテ' %>
      <%= p.select :term,  %w(1 2 3 4 5 6 7 8 9 10 11 12), class: 'form-control' %>
      期
    </div>
<% end %>

app/views/admin/user/index.html.erb
<div class="col-md-10 col-md-offset-1">
  <%= link_to '新規登録', new_admin_user_path, class: 'btn btn-default' %>
  <div class="panel panel-default">
    <div class="panel-heading">ユーザ一覧</div>
    <table class="table">
      <thead>
      <tr>
        <th>ID</th>
        <th>名前</th>
        <th>メールアドレス</th>
        <th>トビタテ期</th>
        <th>アドミン</th>
        <th colspan="2">アクション</th>
      </tr>
      </thead>
      <tbody>
      <% @users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td><%= user.profile.name %></td>
            <td><%= user.email %></td>
            <td><%= user.profile.term %></td>
            <td><%= user.is_admin %></td>
            <td><%= link_to '編集', '#' %></td>
            <td><%= link_to '削除', '#' %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>

</div>

app/views/admin/user/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <h3>新規ユーザー登録</h3>
  <%= form_for @user, url: admin_user_index_path do |f| %>
      <%= render 'shared/error_message', object: f.object %>
      <%= render 'admin/user/form', f:f %>
      <%= f.submit '作成する', class: 'btn btn-primary' %>
  <% end %>
</div>