config/routes.rb
Rails.application.routes.draw do

  mount_roboto
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  namespace :admin do
    resources :user, only: [:new, :create, :index]
  end

  namespace :user do
    ################
    # User profile
    ########
    resources :profile, only: [:index, :update]
    # To avoid adding user number as parameter like :id
    get 'profile/edit', to: 'profile#edit'

    ################
    # User project
    ########
    resources :projects
  end

  ################
  # Devise setting
  ########
  devise_for :users, only: [:sign_in, :sign_out, :session, :password]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  # Open Project
  resources :projects, only: [:index, :show]

  root 'static_page#index'
end

app/views/layouts/_analytics.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-51810510-11"></script>
<script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-51810510-11');
</script>

app/views/layouts/_footer.html.erb
<div class="bg-dark text-white">
  <div class="container">
    <div class="row">
      <div class="p-4 col-md-3">
        <h2 class="mb-4 text-secondary">とまりぎ</h2>
        <p class="text-white">とまりぎ、は <a href="http://www.tobitate.mext.go.jp/" target="_blank" rel="noopener noreferrer" class="text-white">トビタテ!留学JAPAN日本代表プログラム</a>における同窓会組織です。</p>
      </div>
      <div class="p-4 col-md-3">
        <h2 class="mb-4 text-secondary">サイトマップ</h2>
        <ul class="list-unstyled">
          <li>
            <%= link_to 'ホーム', root_path, class: 'text-white' %>
          </li>
          <li>
            <%= link_to 'プロジェクト一覧', projects_path, class: 'text-white' %>
          </li>
          <li>
            <%= link_to 'https://goo.gl/forms/XSYWq1gfRhvLGrB02', class: 'text-white', :target => '_blank' do %>
                プロジェクト報告 <i class="fa fa-external-link" aria-hidden="true"></i>
            <% end %>
          </li>
        </ul>
      </div>
      <div class="p-4 col-md-3">
        <h2 class="mb-4 text-secondary">Contact</h2>
        <p>
          <a href="mailto:info@tobitate-tomarigi.org" class="text-white"><i class="fa d-inline mr-3 text-secondary fa-envelope-o"></i>info@tobitate-tomarigi.org</a>
        </p>
      </div>
      <div class="p-4 col-md-3">
        <h2 class="mb-4 text-secondary">Github</h2>
        <div class="form-group text-white">
          <label for="exampleInputEmail1">バグ報告、要望等はこちらにお願いします。</label>
          <ul>
            <li> - <%= link_to 'Github', 'https://github.com/tomarigi/projects/issues', class: 'text-white' %></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 mt-3">
        <p class="text-center text-white">© Copyright 2017 とまりぎ - All rights reserved. </p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark bgm-base">
  <div class="container">
    <%= link_to 'Tobitate Portfolio β', root_path, :class => 'navbar-brand' %>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"></span> </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item"><%= link_to 'プロジェクト一覧', projects_path, :class => 'nav-link' %></li>
      </ul>
      <form class="form-inline mx-3" action="<%= projects_path %>" method="get">
        <input type="hidden" name="utf8" value="✓">
        <input type="hidden" name="commit" value="検索！">
        <input class="form-control mr-2" type="text" name="q[title_or_description_cont]" placeholder="好きな文字で検索...">
        <button class="btn btn-primary" type="submit">検索</button>
      </form>
      <% if user_signed_in? %>
      <div class="dropdown show">
        <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          メニュー
        </a>

        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <%= link_to 'プロジェクト', user_projects_path, :class => 'dropdown-item' %>
          <%= link_to 'プロフィール', user_profile_index_path, :class => 'dropdown-item' %>
          <div class="dropdown-divider"></div>
          <% if current_user.admin? %>
              <%= link_to 'ユーザー管理', admin_user_index_path, :class => 'dropdown-item' %>
          <% end %>
          <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, :class => 'dropdown-item' %>
        </div>
      </div>
      <% else %>
          <%= link_to 'ログイン', new_user_session_path, :class => 'nav-link text-white' %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_meta.html.erb
<title><%= full_title(yield(:title)) %></title>
<%= csrf_meta_tags %>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content=<%= full_description(yield(:description)) %>>
<%= favicon_link_tag('favicon.ico') %>
<!-- Apple Touch Icon (at least 200x200px) -->
<%= favicon_link_tag('favicon.ico',
                     {:rel => 'apple-touch-icon',
                      :sizes => '180x180',
                      :type => 'image/png'}) %>
<!-- To run web application in full-screen -->
<meta name="apple-mobile-web-app-capable" content="yes">
<!-- Status Bar Style (see Supported Meta Tags below for available values) -->
<!-- Has no effect unless you have the previous meta tag -->
<meta name="apple-mobile-web-app-status-bar-style" content="black">
<!-- Microsoft Tiles -->
<meta name="application-name" content="Tomarigi Portfolio"/>
<meta name="msapplication-square70x70logo" content="msapplication/small.jpg"/>
<meta name="msapplication-square150x150logo" content="msapplication/medium.jpg"/>
<meta name="msapplication-wide310x150logo" content="msapplication/wide.jpg"/>
<meta name="msapplication-square310x310logo" content="msapplication/large.jpg"/>
<meta name="msapplication-TileColor" content="#004EA3"/>

<!-- Facebook Open Graph -->
<meta property="og:type" content="website">
<meta property="og:url" content=<%= Settings.site.url %>>
<meta property="og:title" content=<%= full_title(yield(:title)) %>>
<meta property="og:image" content="https://example.com/image.jpg">
<meta property="og:description" content=<%= full_description(yield(:description)) %>>
<meta property="og:site_name" content="Tomarigi Portfolio">
<meta property="og:locale" content="ja_JP">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">

<!-- Twitter Card -->
<meta name="twitter:card" content=<%= full_description(yield(:description)) %>>
<meta name="twitter:site" content="@ryugakujapan">
<meta name="twitter:creator" content="@goingmywaysp">
<meta name="twitter:url" content=<%= Settings.site.url %>>
<meta name="twitter:title" content=<%= full_title(yield(:title)) %>>
<meta name="twitter:description" content=<%= full_description(yield(:description)) %>>
<meta name="twitter:image" content="/msapplication/wide.jpg">

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja" dir="ltr">
  <head>
    <%= render 'layouts/meta' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/earlyaccess/notosansjapanese.css" rel="stylesheet" />
    <%= render 'layouts/analytics' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
  <%= render 'shared/flash' %>
  <%= yield %>
  <%= render 'layouts/footer' %>
  </body>
</html>